# -*- coding: utf-8 -*-
"""Binomial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19w-JFlroGTr3lr_HizLvTReejOtJ_P1f
"""

import math
class Binomial():
  def __init__(self):
    self.p = 0
    self.x = 0
    self.n = 0
    self.q = 1-self.p
    self.eValue = 0
    self.dPadrao = 0
  
  def setP(self,p):
    self.p = p
    self.q = 1-p
  
  def getP(self):
    return self.p
  
  def setN(self,n):
    self.n = n
  
  def getN(self):
    return self.N
  
  def setX(self,x):
    self.x = x
  
  def getX(self):
    return self.x

  def pMissing(self):
    self.p = self.x/self.n
    self.eValue = self.p*self.n
    self.q = 1-self.p
    var = self.p*self.q*self.n
    self.dPadrao = math.sqrt(var)
    print("Intervalo à esquerda:",(self.eValue-2*self.dPadrao)/self.n)
    print("Intervalo à direita:",(self.eValue+2*self.dPadrao)/self.n)

  def xMissing(self):
    self.eValue = self.n*self.p
    var = self.n*self.q*self.p
    self.dPadrao = math.sqrt(var)

    print("Intervalo à esquerda:",int(self.eValue-2*self.dPadrao))
    print("Intervalo à direita:",int(self.eValue+2*self.dPadrao))

bin = Binomial()

bin.setX(100)
bin.setN(200)
bin.pMissing()