# -*- coding: utf-8 -*-
"""Investimento-com-aporte

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19w-JFlroGTr3lr_HizLvTReejOtJ_P1f
"""

'''
Analisando um aporte regular em um investimento com juros fixos
'''
class Investimento:
  def __init__(self,aporte,jurosEmDecimal,prazo, intervalo= "meses"):
    self.aporte = aporte
    self.juros = jurosEmDecimal
    self.prazo = prazo
    self.intervalo = intervalo
  
  def setJuros(self,jurosEmDecimal):
    self.juros = 1 + jurosEmDecimal
  
  def setAporte(self,capital):
    self.aporte = aporte
  
  def setPrazo(self,prazo):
    self.prazo = prazo
  
  def setIntervalo(self,intervalo):
    self.intervalo = intervalo
  
  def getAporte(self):
    return self.aporte
  
  def getJuros(self):
    return self.juros

  def getPrazo(self):
    return self.prazo

  def getIntervalo(self):
    return self.intervalo

  def rendimentoAporteMensal(self):
    print("Ao fim do período de",self.prazo,self.intervalo,", você acumularia um montante de:",self.aporte*self.prazo)

    result = self.aporte*((self.juros**(self.prazo+1)-self.juros)/(self.juros-1))
    rend = round((result/(self.aporte*self.prazo)-1)*100,2)
    print("Porém, você decidiu investir a uma taxa de",self.juros,", com aporte de",self.aporte,", e seu valor final é de:", result)
    print("Rendimento de {}%".format(rend))

    return result
  

investimento = Investimento(50000,1.01,12)

investimento.rendimentoAporteMensal()