# -*- coding: utf-8 -*-
"""Assets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q9pkZeIYhONOOAVZzOYlFFYihU6AA3jb
"""

class Assets:
  def __init__(self,name):
    self.name = name
    
  def getName(self):
    return self.name

class Portfolio:
  def __init__(self,name):
    self.name = name
    self.assets = {}

  def newBuy(self,asset,newprice,newquantity):
    name = asset.getName()
    if name in self.assets:
      self.assets[name][0] = (self.assets[name][0] * self.assets[name][1] + newprice * newquantity) / (self.assets[name][1] + newquantity)
      self.assets[name][1] = self.assets[name][1] + newquantity
    else:
      self.assets[name] = [newprice,newquantity]
  
  def newSell(self,asset,sellquantity):
    name = asset.getName()
    if name in self.assets:
      if self.assets[name][1] < sellquantity:
        raise Exception("QUANTIDADE VENDIDA EXCEDE O NÚMERO DE ATIVOS, EFETUE A VENDA NOVAMENTE")
      else:
        self.asset[name][1] = self.asset[name][1] - sellquantity
        if self.asset[name][1] == 0:
          self.asset.pop(name)
    else:
      raise Exception("ESTE PORTIFÓLIO NÃO CONTÉM ESTE ATIVO")
    
  def getCurrentSituation(self,asset,newprice):
    name = asset.getName()
    delta = self.assets[name][1]*self.assets[name][0] - newprice*self.assets[name][1]
    print("Foram comprados",self.assets[name][1],"ativos do",name,", com preço médio equivalente a R$",self.assets[name][0],', e um valor total de R$',self.assets[name][0]*self.assets[name][1])
    print("Comparando com o preço atual do ativo, você opera em:")
    print()
    if delta > 0:
      print('PERDA')
      print("{:.2%}".format(-1*(delta/(self.assets[name][0]*self.assets[name][1]))))
      print('R$-{}'.format(delta))
    elif delta < 0:
      print('GANHO')
      print('{:.2%}'.format(-1*(delta/(self.assets[name][0]*self.assets[name][1]))))
      print("R${}".format(delta))
    else:
      print("Equal Situation")
    
  def getPortifolio(self):
    print('Portifolio de',self.name)
    for i in self.assets.keys():
      print('Ativo:',i,' Custo:',self.assets[i][0],' Quantidade:',self.assets[i][1])
    print()
  
  def setAsset(self,asset,newprice,newquantity):
    self.assets[asset.getName()] = [newprice,newquantity]

Pedro = Portfolio('Pedro')
Carlos = Portfolio('Carlos')

petrobras = Assets('PETR4')
engie = Assets('ENGI11')
banco_do_brasil = Assets('BBAS3')
magalu = Assets('MGLU3')

Pedro.newBuy(petrobras,23.54,30)
Carlos.newBuy(petrobras,22.31,45)
Pedro.newBuy(banco_do_brasil,29.48,20)
Carlos.newBuy(engie,41.73,10)
Pedro.newBuy(magalu,21.73,40)

Pedro.getPortifolio()
Carlos.getPortifolio()

Pedro.getCurrentSituation(magalu, 6.09)